name: ds_env
channels:
    - conda-forge
    - defaults
dependencies:
    - pip
    - python
    - numpy
    - sympy
    - openblas
    - swig
    - pip:
        - amici
        - pypesto
        - petab

# versions I used
# pip-22.2.2
# python-3.10.6
# numpy-1.23.2
# sympy-1.10.1
# openblas-0.3.21
# swig-4.0.2
